// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fadonnchefxkrsbddflk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZG9ubmNoZWZ4a3JzYmRkZmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTgxNTQsImV4cCI6MjA2MTU5NDE1NH0.rMwsVBFK4gh2HzFQwxTeXp_WEhtrvAjj-6G6lQAnH6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);